### ISSUE TITLE
Exemplo de programa

### ISSUE THREAD

**Issue by hugotiburtino** [lucastiburtino/deslocamentos#1]
Oi Lucas,

ótimo projeto!

Você pensa em algo como isso aqui?
https://www2.scdp.gov.br/tutoriais/scdp_solicitantes/html/demo_5.html

Teria alguma diferença relevante a ser apontada?

Abraços

**Comment by lucastiburtino** [comment]
Olá, Hugo!

Na verdade, o SCDP é o Sistema em que se cadastra o deslocamento para efeitos de concessão de diárias e passagens de forma efetiva e que impacta na execução financeira e orçamentária.

O SCDP, no entanto, não compreende uma etapa anterior que é a autorização do deslocamento pela autoridade competente. Uma vez autorizado é que é possível cadastrar um deslocamento no SCDP. Assim, a ideia do projeto é sistematizar esse passo anterior que geralmente é realizado de forma não padronizada entre os órgãos federais e geralmente sem grande agilidade ou segurança para quem autoriza.

**Comment by hugotiburtino** [comment]
Entendi. Valeu pela explicação.
Precisamos esclarecer alguns detalhes do produto. 
Como deve se dar a comunicação entre os computadores: usando a rede local ou por meio de um servidor? 
Todo o processo se daria por meio de um programa a ser instalado no computador individual? Ou forneceríamos uma página na inter(ou intra)net e o programa rodaria num servidor?

Não precisamos exclarecer todas as questões de uma só vez. Vamos abrindo algumas 'issues' para ir esclarecendo esses pontos. 

PS: nesse meio tempo, fiz uma 'pull request' já dando uma ideia de como fazer a interface gráfica caso o programa deva ser um programa a ser baixado e instalado em cada máquina. Se é nisso que você está pensando, ótimo. Se não, fica à vontade para recusar.
