### ISSUE TITLE
Programa a ser instalado ou aplicativo da web?

### ISSUE THREAD

**Issue by hugotiburtino** [lucastiburtino/deslocamentos#3]
O título já é auto-explicativo:
Você pensa em que o programa seja um aplicativo a ser baixado e instalado?
Ou seria uma site (talvez restrito aos usários de uma intranet) a ser hospedado num servidor, o qual faria a comunicação entre as contas dos usuários? 

Cada um desses tem seus pró e contra. P.ex. a utilização de um servidor precisaria da autorização da autoridade competente para poder funcionar, ao passo que um programa instalável talvez precise fazer a comunicação de modo indireto, mas seria independente de um servidor.

Alternativamente, pode-se usar um servidor externo ao do órgão, mas aí envolveria outras pessoas e sistemas, o que põe um risco ao sigilo.

**Comment by lucastiburtino** [comment]
Acredito que o ideal seria realmente uma solução web hospedada no servidor do órgão. Desta forma, seria possível, inclusive, futuramente pensar em formas de importar dados como localização de usuários, atualização dos nomes dos setores diante da publicação de novo regimento interno, etc.

**Comment by hugotiburtino** [comment]
:+1: massa, vamos nessa :relaxed:
